export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH = 'USER_AUTH';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_TOKEN = 'USER_TOKEN';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_BY_NAME = 'FETCH_USER_BY_NAME';

export const FETCH_TWEETS = 'FETCH_TWEETS';
export const FETCH_USER_TWEETS = 'FETCH_USER_TWEETS';
export const CREATE_NEW_TWEET = 'CREATE_NEW_TWEET';
export const FETCH_TWEET_LIKES = 'FETCH_TWEET_LIKES';
export const FETCH_TWEET_COMMENTS = 'FETCH_TWEET_COMMENTS';
export const DELETE_TWEET = 'DELETE_TWEET';

export const LIKE_A_TWEET = 'LIKE_A_TWEET';
export const UNLIKE_A_TWEET = 'UNLIKE_A_TWEET';
