export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_BY_NAME = 'FETCH_USER_BY_NAME';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_TWEETS = 'FETCH_TWEETS';
export const FETCH_USER_TWEETS = 'FETCH_USER_TWEETS';
export const CREATE_NEW_TWEET = 'CREATE_NEW_TWEET';
export const FETCH_TWEET_LIKES = 'FETCH_TWEET_LIKES';
export const FETCH_TWEET_COMMENTS = 'FETCH_TWEET_COMMENTS';
export const DELETE_TWEET = 'DELETE_TWEET';

export const LIKE_A_TWEET = 'LIKE_A_TWEET';
export const UNLIKE_A_TWEET = 'UNLIKE_A_TWEET';

export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH = 'USER_AUTH';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_TOKEN = 'USER_TOKEN';
export const CLEAR_ERROR = 'CLEAR_ERROR';
